import { normalizeKeyword } from "./text";
import type { AnchorLanguagePack } from "./types";

export const DEFAULT_LANGUAGE_PACK: AnchorLanguagePack = {
  genericAnchors: [
    "also see",
    "conclusion",
    "faq",
    "frequently asked questions",
    "further reading",
    "introduction",
    "learn more",
    "references",
    "read more",
    "related",
    "related articles",
    "see also",
    "sources",
    "summary",
  ],
  fallbackAnchorFillerWords: [
    "best",
    "guide",
    "how",
    "is",
    "these",
    "this",
    "tips",
    "what",
    "when",
    "where",
    "why",
  ],
  stopwords: [
    "a",
    "about",
    "also",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "by",
    "for",
    "from",
    "how",
    "in",
    "is",
    "it",
    "of",
    "on",
    "or",
    "the",
    "this",
    "to",
    "what",
    "when",
    "where",
    "with",
    "you",
    "your",
  ],
  weakAnchorStartWords: [
    "also",
    "because",
    "check",
    "do",
    "does",
    "how",
    "if",
    "read",
    "see",
    "these",
    "this",
    "use",
    "what",
    "when",
    "where",
    "which",
    "why",
  ],
  weakAnchorEndWords: [
    "are",
    "can",
    "do",
    "does",
    "have",
    "it",
    "often",
    "this",
    "you",
  ],
};

export const DUTCH_LANGUAGE_PACK: AnchorLanguagePack = {
  genericAnchors: [
    "bekijk ook",
    "betrouwbare externe informatie",
    "bronnen",
    "conclusie",
    "externe bronnen",
    "externe informatie",
    "gerelateerde artikelen",
    "introductie",
    "lees meer",
    "samenvatting",
    "snelle samenvatting",
    "veelgestelde vragen",
  ],
  fallbackAnchorFillerWords: [
    "deze",
    "dit",
    "doe",
    "helpt",
    "herken",
    "hoe",
    "is",
    "meest",
    "oorzaak",
    "oorzaken",
    "vaak",
    "waar",
    "wanneer",
    "waarom",
    "wat",
    "welke",
    "zo",
  ],
  stopwords: [
    "aan",
    "als",
    "bij",
    "dat",
    "de",
    "die",
    "dit",
    "een",
    "en",
    "er",
    "het",
    "hoe",
    "in",
    "is",
    "je",
    "kan",
    "met",
    "niet",
    "of",
    "om",
    "op",
    "te",
    "tot",
    "van",
    "voor",
    "wat",
    "waar",
    "wanneer",
    "we",
    "zijn",
  ],
  weakAnchorStartWords: [
    "bekijk",
    "deze",
    "dit",
    "gebruik",
    "herken",
    "hoe",
    "lees",
    "vaak",
    "wanneer",
    "waar",
    "waarom",
    "wat",
    "welke",
  ],
  weakAnchorEndWords: [
    "dan",
    "deze",
    "dit",
    "hebt",
    "je",
    "kan",
    "vaak",
  ],
};

// TODO: Allow config/semantic.json to override or extend these packs, e.g.
// quickWins.genericAnchors, quickWins.stopwords, quickWins.languagePacks.
export const ACTIVE_LANGUAGE_PACKS = [DEFAULT_LANGUAGE_PACK, DUTCH_LANGUAGE_PACK];

function mergeLanguagePackValues(key: keyof AnchorLanguagePack) {
  return new Set(
    ACTIVE_LANGUAGE_PACKS.flatMap((pack) => pack[key]).map(normalizeKeyword)
  );
}

export const GENERIC_ANCHORS = mergeLanguagePackValues("genericAnchors");
export const ANCHOR_STOPWORDS = mergeLanguagePackValues("stopwords");
export const FALLBACK_ANCHOR_FILLER_WORDS = mergeLanguagePackValues(
  "fallbackAnchorFillerWords"
);
// Product/domain terms should never be hardcoded here. Corpus-level keyword
// frequency decides whether terms are broad for a specific site.
export const ANCHOR_START_WORDS = mergeLanguagePackValues("weakAnchorStartWords");
export const WEAK_ANCHOR_END_WORDS = mergeLanguagePackValues("weakAnchorEndWords");
export const EDITORIAL_WORDS = new Set([
  ...Array.from(GENERIC_ANCHORS).flatMap((anchor) => anchor.split(/\s+/)),
  "article",
  "articles",
  "external",
  "information",
  "source",
  "topic",
  "artikel",
  "artikelen",
  "betrouwbare",
  "extern",
  "externe",
  "informatie",
  "onderwerp",
]);
export const CTA_WORDS = new Set(
  [
    "appointment",
    "book",
    "buy",
    "call",
    "contact",
    "download",
    "offer",
    "quote",
    "subscribe",
    "afspraak",
    "bel",
    "bestel",
    "contact",
    "download",
    "gratis",
    "koop",
    "offerte",
  ].map(normalizeKeyword)
);
